version: '3'

services:
  ui-translator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped